### ISSUE TITLE
eroc date format is slightly different and causes an error in eroc.py

### ISSUE THREAD

**Issue by jnicho02** [zathras777/pywind#4]
Ironically, on the day that I try out pywind the eroc date in http://www.epowerauctions.co.uk/erocrecord.htm is in a very slightly different format... "27th October 2016" instead of "27 October 2016" which then throws an error in eroc.py line 120 for 

```
pywind roc_prices --export xlsx
```

**Comment by jnicho02** [comment]
#5 should do the do

**Comment by zathras777** [comment]
Good catch!

How about we simply remove the suffixes?

pattern = re.compile('(st|nd|rd|th|,)')
date = pattern.sub('', date)

**Comment by zathras777** [comment]
Merged :-) Thanks
